server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /quant-api/ {
        proxy_pass http://quant-api:8090/;
    }

    location /exchange-api/ {
        proxy_pass http://exchange:8080/;
    }
}
